# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "CLI da Internal Developer Platform: gera projetos padronizados a partir dos templates oficiais."
  homepage "https://github.com/matheusbrauna/forge"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matheusbrauna/forge/releases/download/v0.1.1/forge_0.1.1_darwin_amd64.tar.gz"
      sha256 "4e41200c46964324ab290b7d26cd4243850323fec322d80ed5fc7bbf95aea7df"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matheusbrauna/forge/releases/download/v0.1.1/forge_0.1.1_darwin_arm64.tar.gz"
      sha256 "24f06c0e2ab8ab837e96e5e700d7ff05a85b02b138834753762cbf6a3841c526"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheusbrauna/forge/releases/download/v0.1.1/forge_0.1.1_linux_amd64.tar.gz"
      sha256 "7e9406743fda917bd96a75f6882c615e6a920ed55bb2432b38dca1aa994dc775"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheusbrauna/forge/releases/download/v0.1.1/forge_0.1.1_linux_arm64.tar.gz"
      sha256 "459e71c46dd6f6c74edea24287d11f71cc5dc11007a0e6c8c95662f607205971"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
