# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Forge < Formula
  desc "CLI da Internal Developer Platform: gera projetos padronizados a partir dos templates oficiais."
  homepage "https://github.com/matheusbrauna/forge"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/matheusbrauna/forge/releases/download/v0.2.0/forge_0.2.0_darwin_amd64.tar.gz"
      sha256 "507ad8f0841be05e2ca5a25e5e54f2a87e0c6df06f2839b35c6ca63463cc18f2"

      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/matheusbrauna/forge/releases/download/v0.2.0/forge_0.2.0_darwin_arm64.tar.gz"
      sha256 "004b80e3e7a9a76dea790ecf8ec3c9f54bb58e82859ec18d6009fd8ecd646ecb"

      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheusbrauna/forge/releases/download/v0.2.0/forge_0.2.0_linux_amd64.tar.gz"
      sha256 "52249501641f6cedc843b172cfcbc1564459ed5879b0b254bb2ad431d0e8bca3"
      define_method(:install) do
        bin.install "forge"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/matheusbrauna/forge/releases/download/v0.2.0/forge_0.2.0_linux_arm64.tar.gz"
      sha256 "7738d2aa48142461476c1b5dbefc310dba73d9b4a845977bc8de748cf9512aa2"
      define_method(:install) do
        bin.install "forge"
      end
    end
  end

  test do
    system "#{bin}/forge", "version"
  end
end
